server:
  port: 8086

logging:
  level:
    root: error
    net.ahwater.dataServ: debug

spring:
  jmx:
    enabled: false
  application:
    name: dataServ

  main:
    banner-mode: 'OFF'
  jackson:
    default-property-inclusion: ALWAYS
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-bigdecimal-as-plain: true
  datasource:
    dynamic:
      master:
        url: jdbc:mysql://10.34.1.74:3306/cas?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ahwt
        password: ahwater321
      slave:
        slave_1:
          url: jdbc:sqlserver://10.34.1.1:1500;DatabaseName=AHSQ2005
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          username: websl_mas
          password: Swj2014



mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: net.ahwater.dataServ.entity.po
  global-config:
    db-config:
      db-type: sql_server
      id-type: auto
      capital-mode: false
      table-prefix: d_
      table-underline: true
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true

project-config:
  passwordSalt: WaterSsoServices