server:
  port: 8082
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: net.ahwater.zjk.entity.po
  global-config:
    db-config:
      db-type: sql_server
      id-type: auto
      capital-mode: false
      table-prefix: WT_
      table-underline: true
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.11.165;DatabaseName=WATER_XSK
    username: sa
    password: ahWater321
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
  rabbitmq:
    host: 192.168.0.140
    port: 5672
    username: rabbit
    password: rabbit$
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 50MB